import { boolean, index, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

export const role = pgEnum("role", ["admin", "client"]);
export const projectStatus = pgEnum("project_status", ["draft", "awaiting_acceptance", "awaiting_deposit", "active", "awaiting_final_payment", "completed", "cancelled"]);
export const invoiceStatus = pgEnum("invoice_status", ["draft", "issued", "partially_paid", "paid", "overdue", "cancelled"]);
export const paymentMethod = pgEnum("payment_method", ["paypal", "ccp_transfer"]);

const audit = { createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() };

export const users = pgTable("users", { id: uuid("id").primaryKey().defaultRandom(), role: role("role").notNull(), email: varchar("email", { length: 255 }).notNull(), name: varchar("name", { length: 160 }).notNull(), locale: varchar("locale", { length: 2 }).notNull().default("fr"), ...audit }, (t) => [uniqueIndex("users_email_unique").on(t.email)]);
export const clients = pgTable("clients", { id: uuid("id").primaryKey().defaultRandom(), publicId: varchar("public_id", { length: 20 }).notNull(), legalName: varchar("legal_name", { length: 255 }).notNull(), billingAddress: text("billing_address"), primaryUserId: uuid("primary_user_id").references(() => users.id), ...audit }, (t) => [uniqueIndex("clients_public_id_unique").on(t.publicId)]);
export const projects = pgTable("projects", { id: uuid("id").primaryKey().defaultRandom(), publicId: varchar("public_id", { length: 20 }).notNull(), clientId: uuid("client_id").notNull().references(() => clients.id), name: varchar("name", { length: 255 }).notNull(), locale: varchar("locale", { length: 2 }).notNull(), currency: varchar("currency", { length: 3 }).notNull(), totalAmount: numeric("total_amount", { precision: 12, scale: 2 }).notNull(), status: projectStatus("status").notNull().default("draft"), scope: text("scope").notNull(), ...audit }, (t) => [uniqueIndex("projects_public_id_unique").on(t.publicId), index("projects_client_idx").on(t.clientId)]);
export const generatedDocuments = pgTable("generated_documents", { id: uuid("id").primaryKey().defaultRandom(), projectId: uuid("project_id").notNull().references(() => projects.id), kind: varchar("kind", { length: 32 }).notNull(), locale: varchar("locale", { length: 2 }).notNull(), templateVersion: varchar("template_version", { length: 32 }).notNull(), storageKey: text("storage_key").notNull(), sha256: varchar("sha256", { length: 64 }).notNull(), sourceSnapshot: jsonb("source_snapshot").notNull(), acceptedAt: timestamp("accepted_at", { withTimezone: true }), ...audit });
export const agreementAcceptances = pgTable("agreement_acceptances", { id: uuid("id").primaryKey().defaultRandom(), documentId: uuid("document_id").notNull().references(() => generatedDocuments.id), signerName: varchar("signer_name", { length: 160 }).notNull(), ipAddress: varchar("ip_address", { length: 64 }).notNull(), userAgent: text("user_agent").notNull(), acceptedAt: timestamp("accepted_at", { withTimezone: true }).notNull().defaultNow() });
export const invoices = pgTable("invoices", { id: uuid("id").primaryKey().defaultRandom(), publicId: varchar("public_id", { length: 20 }).notNull(), projectId: uuid("project_id").notNull().references(() => projects.id), amount: numeric("amount", { precision: 12, scale: 2 }).notNull(), currency: varchar("currency", { length: 3 }).notNull(), status: invoiceStatus("status").notNull().default("draft"), dueAt: timestamp("due_at", { withTimezone: true }), isDeposit: boolean("is_deposit").notNull().default(false), ...audit }, (t) => [uniqueIndex("invoices_public_id_unique").on(t.publicId), index("invoices_project_idx").on(t.projectId)]);
export const payments = pgTable("payments", { id: uuid("id").primaryKey().defaultRandom(), invoiceId: uuid("invoice_id").notNull().references(() => invoices.id), method: paymentMethod("method").notNull(), providerReference: varchar("provider_reference", { length: 255 }), amount: numeric("amount", { precision: 12, scale: 2 }).notNull(), proofStorageKey: text("proof_storage_key"), confirmedAt: timestamp("confirmed_at", { withTimezone: true }), ...audit });
export const auditEvents = pgTable("audit_events", { id: uuid("id").primaryKey().defaultRandom(), actorId: uuid("actor_id").references(() => users.id), entityType: varchar("entity_type", { length: 48 }).notNull(), entityId: uuid("entity_id").notNull(), action: varchar("action", { length: 96 }).notNull(), metadata: jsonb("metadata").notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
