import { NextRequest, NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { requireAdmin } from "@/lib/authz";
import { db } from "@/lib/db";
import { auditEvents, clientContacts, clients, invoiceItems, invoices, projectItems, projects, users } from "@/lib/db/schema";
import { allocatePublicId } from "@/lib/public-ids";
import { issueEmailToken } from "@/lib/email-tokens";
import { accountEmail, sendProjectEmail, smtpConfigured } from "@/lib/mailer";
import { generateProjectDocument } from "@/lib/document-service";
import { depositItems, depositTotal, projectTotal, type ServiceItem } from "@/lib/project-pricing";

const item = z.object({ description:z.string().min(2).max(500), quantity:z.coerce.number().int().min(1).max(999), unitAmount:z.string().regex(/^\d+(\.\d{1,2})?$/) });
const shared = z.object({ projectName:z.string().min(2).max(255), scope:z.string().min(10).max(5000), currency:z.enum(["DZD","EUR","USD"]), locale:z.enum(["fr","en"]).default("fr"), inquiryId:z.string().uuid().optional(), items:z.array(item).min(1).max(50) });
const input = z.discriminatedUnion("clientMode", [shared.extend({clientMode:z.literal("existing"),clientId:z.string().uuid(),contactId:z.string().uuid().optional()}),shared.extend({clientMode:z.literal("new"),clientName:z.string().min(2).max(255),contactName:z.string().min(2).max(160),contactEmail:z.string().email()})]);

export async function POST(request: NextRequest) {
  const admin = await requireAdmin(); const parsed = input.safeParse(await request.json());
  if (!parsed.success) return NextResponse.json({ error:"Complete the client, project, and at least one service item." }, { status:400 });
  const data=parsed.data, projectId=crypto.randomUUID(), invoiceId=crypto.randomUUID(), items=data.items as ServiceItem[];
  let clientId:string, clientPublicId:string|undefined, contact:{id:string;userId:string|null;email:string;name:string}, recipient:{id:string;email:string;name:string;locale:string;needsInvite:boolean}|undefined;
  if(data.clientMode==="existing") {
    const client=await db.query.clients.findFirst({where:eq(clients.id,data.clientId)}); if(!client)return NextResponse.json({error:"Selected client no longer exists."},{status:404}); clientId=client.id;
    const contacts=await db.select().from(clientContacts).where(eq(clientContacts.clientId,clientId)); contact=(data.contactId?contacts.find(c=>c.id===data.contactId):contacts.find(c=>c.isPrimary)??contacts[0])!; if(!contact)return NextResponse.json({error:"Select or add a contact before creating this project."},{status:400});
    let user=contact.userId?await db.query.users.findFirst({where:eq(users.id,contact.userId)}):await db.query.users.findFirst({where:eq(users.email,contact.email)}); if(!user){[user]=await db.insert(users).values({name:contact.name,email:contact.email,status:"pending_verification"}).returning(); await db.update(clientContacts).set({userId:user.id}).where(eq(clientContacts.id,contact.id));}
    recipient={id:user.id,email:user.email,name:user.name,locale:user.locale,needsInvite:user.status!=="active"};
  } else {
    clientId=crypto.randomUUID(); clientPublicId=await allocatePublicId("CL"); const email=data.contactEmail.toLowerCase(); let user=await db.query.users.findFirst({where:eq(users.email,email)}); if(!user)[user]=await db.insert(users).values({email,name:data.contactName,status:"pending_verification",locale:data.locale}).returning(); contact={id:"",userId:user.id,email,name:data.contactName}; recipient={id:user.id,email, name:user.name,locale:user.locale,needsInvite:user.status!=="active"};
  }
  const [projectPublicId,invoicePublicId]=await Promise.all([allocatePublicId("PRJ"),allocatePublicId("INV")]); const total=projectTotal(items), deposit=depositTotal(items), depositLines=depositItems(items), dueAt=new Date(Date.now()+7*86400000);
  await db.transaction(async tx=>{ if(data.clientMode==="new"){await tx.insert(clients).values({id:clientId,publicId:clientPublicId!,legalName:data.clientName,primaryUserId:recipient!.id});await tx.insert(clientContacts).values({clientId,userId:recipient!.id,email:recipient!.email,name:data.contactName,isPrimary:true});} await tx.insert(projects).values({id:projectId,publicId:projectPublicId,clientId,inquiryId:data.inquiryId,name:data.projectName,locale:data.locale,currency:data.currency,totalAmount:total,scope:data.scope,status:"awaiting_acceptance"}); await tx.insert(projectItems).values(items.map(i=>({projectId,description:i.description,quantity:i.quantity,unitAmount:i.unitAmount}))); await tx.insert(invoices).values({id:invoiceId,publicId:invoicePublicId,projectId,amount:deposit,currency:data.currency,status:"issued",dueAt,isDeposit:true}); await tx.insert(invoiceItems).values(depositLines.map(i=>({invoiceId,description:i.description,quantity:i.quantity,unitAmount:i.unitAmount}))); await tx.insert(auditEvents).values({actorId:admin.id,entityType:"project",entityId:projectId,action:"project_created",metadata:{clientPublicId,projectPublicId,invoicePublicId,inquiryId:data.inquiryId}}); });
  try { const agreement=await generateProjectDocument(projectId,"agreement"), invoiceDoc=await generateProjectDocument(projectId,"invoice"), welcome=await generateProjectDocument(projectId,"welcome_packet"); let invitationSent=false; if(!smtpConfigured()) throw new Error("Email delivery is not configured."); const token=recipient!.needsInvite?await issueEmailToken(recipient!.id,"invite"):undefined, invitation=token?accountEmail("invite",token,recipient!.locale):undefined; await sendProjectEmail({to:recipient!.email,subject:invitation?.subject??`New Rezo project: ${data.projectName}`,html:`${welcome.html}<div style="background:#050505;color:#fff;padding:24px"><p>${invitation?.body??"Your Rezo workspace has a new project. Sign in to review the agreement and next steps."}</p><p><a style="color:#fff" href="${invitation?.href??`${request.nextUrl.origin}/sign-in`}">${invitation?"Set up your workspace":"Open Rezo"}</a></p>${invoiceDoc.html}</div>`,attachments:[{filename:invoiceDoc.filename,content:invoiceDoc.pdf,contentType:"application/pdf"},{filename:welcome.filename,content:welcome.pdf,contentType:"application/pdf"}]}); invitationSent=true; await db.insert(auditEvents).values({actorId:admin.id,entityType:"project",entityId:projectId,action:"documents_generated",metadata:{agreement:agreement.id,invoice:invoiceDoc.id,welcome:welcome.id,invitationSent}}); return NextResponse.json({projectId,projectPublicId,invoicePublicId,detailUrl:`/admin/projects/${projectId}`,invitationSent},{status:201}); }
  catch(error) { const message=error instanceof Error?error.message:"Unknown document delivery failure"; await db.insert(auditEvents).values({actorId:admin.id,entityType:"project",entityId:projectId,action:"document_delivery_failed",metadata:{message}}); return NextResponse.json({projectId,projectPublicId,invoicePublicId,detailUrl:`/admin/projects/${projectId}`,invitationSent:false,deliveryError:message},{status:201}); }
}
