import { FileText, FolderOpen, ReceiptText, Settings } from "lucide-react";
import { and, desc, eq } from "drizzle-orm";
import { PortalShell } from "@/components/portal-shell";
import { AgreementAction, CcpProofUpload, KickoffBrief, ProjectFiles, ProjectSwitcher } from "@/components/client-workspace-actions";
import { AccountSettings } from "@/components/account-settings";
import { InvoiceActions } from "@/components/invoice-actions";
import { requireUser } from "@/lib/authz";
import { db } from "@/lib/db";
import { clientContacts, generatedDocuments, invoices, payments, projectFiles, projectIntakes, projectItems, projects } from "@/lib/db/schema";

export const dynamic="force-dynamic";
const pages={project:{title:"Project",copy:"Scope, service items, and your optional kickoff brief."},documents:{title:"Documents",copy:"Generated and immutable project records."},invoices:{title:"Invoices",copy:"Payment requests and their review status."},files:{title:"Files",copy:"Shared project files and client assets."},settings:{title:"Settings",copy:"Manage your profile and session."}} as const;
export default async function SectionPage({params,searchParams}:{params:Promise<{section:string}>;searchParams:Promise<{project?:string}>}){const user=await requireUser(),{section}=await params,page=pages[section as keyof typeof pages];if(!page)return <PortalShell role={user.role}><div className="content"><h1>Page not found</h1></div></PortalShell>;if(section==="settings")return <PortalShell role={user.role}><PageHead title={page.title} copy={page.copy}/><AccountSettings name={user.name} locale={user.locale}/></PortalShell>;const selected=(await searchParams).project;const rows=user.role==="admin"?await db.select().from(projects).orderBy(desc(projects.updatedAt)):await db.select({id:projects.id,publicId:projects.publicId,name:projects.name,status:projects.status,scope:projects.scope,currency:projects.currency,totalAmount:projects.totalAmount,clientId:projects.clientId,createdAt:projects.createdAt,updatedAt:projects.updatedAt,locale:projects.locale,inquiryId:projects.inquiryId,deliverables:projects.deliverables,startsAt:projects.startsAt,dueAt:projects.dueAt}).from(projects).innerJoin(clientContacts,and(eq(clientContacts.clientId,projects.clientId),eq(clientContacts.userId,user.id))).orderBy(desc(projects.updatedAt));const project=rows.find(p=>p.publicId===selected)??rows[0];if(!project)return <PortalShell role={user.role}><PageHead title={page.title} copy={page.copy}/><Empty/></PortalShell>;const navProjects=rows.map(p=>({publicId:p.publicId,name:p.name,status:p.status}));const shell=(content:React.ReactNode)=><PortalShell role={user.role} projectPublicId={project.publicId}><div className="content"><PageHead title={page.title} copy={page.copy}/><ProjectSwitcher projects={navProjects} current={project.publicId} section={section}/>{content}</div></PortalShell>;
if(section==="project"){const [items,intake]=await Promise.all([db.select().from(projectItems).where(eq(projectItems.projectId,project.id)),db.query.projectIntakes.findFirst({where:eq(projectIntakes.projectId,project.id)})]);const answers=(intake?.answers??{}) as Record<string,string>;return shell(<><section className="record-list"><div className="record-row"><span><b>{project.name}</b><small>{project.publicId} · {project.status.replaceAll("_"," ")}</small><small>{project.scope}</small></span></div>{items.map(i=><div className="record-row" key={i.id}><span><b>{i.description}</b><small>{i.quantity} × {project.currency} {i.unitAmount}</small></span><strong>{project.currency} {(Number(i.unitAmount)*i.quantity).toFixed(2)}</strong></div>)}</section>{user.role==="client"&&<section className="workspace-section"><h2>Kickoff brief</h2><p className="lead">Optional context that helps us start with the right priorities.</p><KickoffBrief projectId={project.id} initial={answers}/></section>}</>)}
if(section==="documents"){const docs=await db.select().from(generatedDocuments).where(eq(generatedDocuments.projectId,project.id)).orderBy(desc(generatedDocuments.createdAt));return shell(<section className="record-list">{docs.map(d=><div className="record-row" key={d.id}><span><b>{d.kind.replaceAll("_"," ")}</b><small>{d.templateVersion} · {d.createdAt.toLocaleDateString()}</small></span><a className="button button-quiet" href={`/api/documents/${d.id}/download`}>Download PDF</a>{d.kind==="agreement"&&user.role==="client"&&<AgreementAction documentId={d.id} accepted={Boolean(d.acceptedAt)}/>}</div>)}</section>)}
if(section==="invoices"){const [bills,proofs]=await Promise.all([db.select().from(invoices).where(eq(invoices.projectId,project.id)).orderBy(desc(invoices.createdAt)),db.select().from(payments).innerJoin(invoices,eq(payments.invoiceId,invoices.id)).where(eq(invoices.projectId,project.id)).orderBy(desc(payments.createdAt))]);return shell(<section className="record-list">{bills.map(b=>{const proof=proofs.find(row=>row.payments.invoiceId===b.id)?.payments,agreementAccepted=project.status!=="awaiting_acceptance";return <div className="record-row" key={b.id}><span><b>{b.publicId}</b><small>{b.isDeposit?"Deposit":"Final"} · due {b.dueAt?.toLocaleDateString()??"on issue"}</small></span><strong>{b.currency} {b.amount}</strong><em className="status status-warning">{b.status}</em>{agreementAccepted&&b.status!=="paid"&&(b.currency==="DZD"?<CcpProofUpload invoiceId={b.id} status={proof?.reviewStatus??"new"} note={proof?.reviewNote}/>:<InvoiceActions invoiceId={b.id} payable />)}</div>})}</section>)}
const files=await db.select().from(projectFiles).where(eq(projectFiles.projectId,project.id)).orderBy(desc(projectFiles.createdAt));return shell(<ProjectFiles projectId={project.id} files={files.map(f=>({...f,createdAt:f.createdAt.toISOString()}))}/>)}
function PageHead({title,copy}:{title:string;copy:string}){return <section className="page-heading"><div><p className="eyebrow">REZO WORKSPACE</p><h1>{title}</h1><p className="lead">{copy}</p></div></section>};function Empty(){return <section className="empty-state"><FolderOpen size={22}/><h2>No workspace available</h2><p>Your administrator will share a project when it is ready.</p></section>}
