"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";

async function post(path: string, body: unknown) { const res = await fetch(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); return { ok: res.ok, body: await res.json().catch(() => ({})) as { error?: string } }; }
export function SignInForm() { const router = useRouter(); const [error, setError] = useState(""); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const v=Object.fromEntries(new FormData(e.currentTarget)); const r=await post("/api/auth/sign-in",v); if(r.ok) router.push("/"); else setError(r.body.error ?? "Invalid email or password."); } return <AuthFrame title="Sign in securely." lead="Use your verified email address and password to access your workspace."><form onSubmit={submit}><label>Email address<input name="email" type="email" autoComplete="email" required /></label><label>Password<input name="password" type="password" autoComplete="current-password" required /></label>{error&&<p className="form-error">{error}</p>}<button className="button">Sign in</button></form><small><Link href="/forgot-password">Forgot password?</Link> · <Link href="/sign-up">Create an account</Link></small></AuthFrame>; }
export function SignUpForm() { const [done,setDone]=useState(false),[error,setError]=useState(""); async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const password=String(f.get("password"));if(password!==f.get("confirmPassword"))return setError("Passwords do not match.");const r=await post("/api/auth/sign-up",{name:f.get("name"),email:f.get("email"),password,acceptedTerms:f.get("acceptedTerms")==="on"});if(r.ok)setDone(true);else setError(r.body.error??"Unable to create account.");} if(done)return <AuthFrame title="Check your email." lead="If the address can be used, a verification link is on its way."><small><Link href="/sign-in">Return to sign in</Link></small></AuthFrame>; return <AuthFrame title="Create your account." lead="Verify your email before accessing the portal."><form onSubmit={submit}><label>Name<input name="name" autoComplete="name" required /></label><label>Email address<input name="email" type="email" autoComplete="email" required /></label><label>Password<input name="password" type="password" minLength={12} autoComplete="new-password" required /></label><label>Confirm password<input name="confirmPassword" type="password" minLength={12} autoComplete="new-password" required /></label><label className="check"><input name="acceptedTerms" type="checkbox" required />I accept the portal terms and privacy notice.</label>{error&&<p className="form-error">{error}</p>}<button className="button">Create account</button></form><small>Already registered? <Link href="/sign-in">Sign in</Link></small></AuthFrame>; }
export function ForgotForm(){const[done,setDone]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();await post("/api/auth/forgot-password",Object.fromEntries(new FormData(e.currentTarget)));setDone(true)}return <AuthFrame title="Reset your password." lead={done?"If the address is registered, a reset link is on its way.":"Enter your account email and we will send a reset link."}>{!done&&<form onSubmit={submit}><label>Email address<input name="email" type="email" autoComplete="email" required /></label><button className="button">Send reset link</button></form>}<small><Link href="/sign-in">Return to sign in</Link></small></AuthFrame>}
export function ResetForm(){const params=useSearchParams();const[error,setError]=useState("");const[done,setDone]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(f.get("password")!==f.get("confirmPassword"))return setError("Passwords do not match.");const r=await post("/api/auth/reset-password",{token:params.get("token"),password:f.get("password")});if(r.ok)setDone(true);else setError(r.body.error??"Unable to reset password.")}return <AuthFrame title="Choose a new password." lead="Use at least 12 characters.">{done?<small>Password updated. <Link href="/sign-in">Sign in</Link></small>:<form onSubmit={submit}><label>New password<input name="password" type="password" minLength={12} required /></label><label>Confirm password<input name="confirmPassword" type="password" minLength={12} required /></label>{error&&<p className="form-error">{error}</p>}<button className="button">Update password</button></form>}</AuthFrame>}
function AuthFrame({title,lead,children}:{title:string;lead:string;children:React.ReactNode}){return <main className="sign-in"><section><p className="eyebrow">REZO CLIENT PORTAL</p><h1>{title}</h1><p>{lead}</p>{children}</section></main>}
