"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";

export function ProjectSwitcher({projects,current,section}:{projects:Array<{publicId:string;name:string;status:string}>;current:string;section:string}){return <label className="project-switcher">Project<select value={current} onChange={e=>location.assign(`/${section}?project=${encodeURIComponent(e.target.value)}`)}>{projects.map(p=><option key={p.publicId} value={p.publicId}>{p.name} · {p.publicId}</option>)}</select></label>}

export function AgreementAction({documentId,accepted}:{documentId:string;accepted:boolean}){const [name,setName]=useState(""),[note,setNote]=useState(accepted?"Agreement accepted.":""),[busy,setBusy]=useState(false);async function accept(){setBusy(true);const r=await fetch(`/api/documents/${documentId}/accept`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({signerName:name})});setNote(r.ok?"Agreement accepted. Your deposit is now available.":(await r.json()).error??"Could not accept agreement.");setBusy(false)}if(accepted)return <p className="form-success">Agreement accepted.</p>;return <div className="inline-action"><label>Legal signer name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Full legal name"/></label><button className="button" disabled={busy||name.trim().length<2} onClick={accept}>{busy?"Accepting…":"Accept agreement"}</button>{note&&<p className="form-error">{note}</p>}</div>}

export function CcpProofUpload({invoiceId,status,note}:{invoiceId:string;status:string;note?:string|null}){const [message,setMessage]=useState(status==="pending"?"Proof submitted for review.":note??"");const [busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=new FormData(e.currentTarget);form.set("invoiceId",invoiceId);const r=await fetch("/api/payments/proof",{method:"POST",body:form});setMessage(r.ok?"Proof submitted for review.":(await r.json()).error??"Could not upload proof.");setBusy(false)}return <section className="payment-proof"><p><b>CCP transfer</b><br/>Send the transfer, then upload its proof for manual review.</p>{status==="rejected"&&<p className="form-error">Re-upload requested: {note}</p>}{status!=="pending"&&<form onSubmit={submit}><input name="proof" type="file" accept="application/pdf,image/png,image/jpeg" required/><button className="button" disabled={busy}>{busy?"Uploading…":"Upload CCP proof"}</button></form>}{status==="pending"&&<p className="form-success">{message}</p>}</section>}

export function ProjectFiles({projectId,files}:{projectId:string;files:Array<{id:string;filename:string;contentType:string;sizeBytes:number;createdAt:string}>}){const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=new FormData(e.currentTarget);form.set("projectId",projectId);const r=await fetch("/api/files",{method:"POST",body:form});setMessage(r.ok?"File uploaded. Refreshing…":(await r.json()).error??"Could not upload file.");setBusy(false);if(r.ok)setTimeout(()=>location.reload(),500)}return <><form className="file-upload" onSubmit={submit}><input name="file" type="file" accept="application/pdf,image/png,image/jpeg,application/zip,text/plain" required/><button className="button" disabled={busy}>{busy?"Uploading…":"Upload file"}</button>{message&&<small>{message}</small>}</form><section className="record-list">{files.map(file=><a className="record-row" href={`/api/files/${file.id}/download`} key={file.id}><span><b>{file.filename}</b><small>{file.contentType} · {Math.ceil(file.sizeBytes/1024)} KB · {new Date(file.createdAt).toLocaleDateString()}</small></span><span className="text-action">Download</span></a>)}</section></>}

const fields=[['goals','Business goals'],['audience','Audience'],['features','Required pages and features'],['assets','Assets and content readiness'],['integrations','Integrations and access'],['launchTarget','Launch target'],['notes','Additional notes']] as const;
export function KickoffBrief({projectId,initial}:{projectId:string;initial:Record<string,string>}){const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const values=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch(`/api/projects/${projectId}/intake`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});setMessage(r.ok?"Kickoff brief saved.":(await r.json()).error??"Could not save the brief.");setBusy(false)}return <form className="setup-form kickoff-brief" onSubmit={submit}>{fields.map(([key,label])=><label key={key}>{label}<textarea name={key} defaultValue={initial[key]??""} required={key!=="notes"}/></label>)}<button className="button" disabled={busy}>{busy?"Saving…":"Save kickoff brief"}</button>{message&&<p className={message.includes("saved")?"form-success":"form-error"}>{message}</p>}</form>}

export function PaymentReview({paymentId,status,note}:{paymentId:string;status:string;note?:string|null}){const [message,setMessage]=useState("");async function decide(decision:"accepted"|"rejected"){const reviewNote=decision==="rejected"?prompt("Reason for the client:")??"":"";if(decision==="rejected"&&!reviewNote)return;const r=await fetch(`/api/admin/payments/${paymentId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision,note:reviewNote})});setMessage(r.ok?"Payment review saved.":(await r.json()).error??"Could not save review.");if(r.ok)setTimeout(()=>location.reload(),400)}return <div className="inline-action"><span className="status status-warning">{status}</span>{note&&<small>{note}</small>}{status==="pending"&&<><button className="button" onClick={()=>decide("accepted")}>Approve proof</button><button className="button button-quiet" onClick={()=>decide("rejected")}>Request re-upload</button></>}{message&&<small>{message}</small>}</div>}

export function DeliveryRetry({projectId}:{projectId:string}){const [message,setMessage]=useState("");async function retry(){const r=await fetch(`/api/admin/projects/${projectId}/resend`,{method:"POST"});setMessage(r.ok?"Project email sent.":(await r.json()).error??"Could not send project email.")}return <div className="inline-action"><button className="button button-quiet" onClick={retry}>Resend project email</button>{message&&<small>{message}</small>}</div>}
