import Link from "next/link";
import { ArrowUpRight, CheckCircle2, ChevronRight, FileCheck2, FolderOpen, ReceiptText, Upload } from "lucide-react";

export function Dashboard() {
  return <div className="content">
    <section className="page-heading"><div><p className="eyebrow">CLIENT PORTAL</p><h1>Your workspace is ready.</h1><p className="lead">Create your first client and project to begin generating agreements, invoices, and onboarding documents.</p></div><Link className="button" href="/setup"><Upload size={16}/> Create first project</Link></section>
    <section className="project-banner"><div className="project-index">01</div><div className="project-copy"><p className="eyebrow">FIRST-RUN SETUP</p><h2>Create real records, not mock data.</h2><p>The setup flow writes your client, project, and 20% deposit invoice to Neon.</p></div><Link className="button button-quiet" href="/setup">Open setup <ChevronRight size={16}/></Link></section>
    <section className="dashboard-grid"><div className="main-column"><div className="section-title"><div><p className="eyebrow">WORKSPACE AREAS</p><h2>Start from the right place</h2></div></div><div className="document-list"><Link className="document-row" href="/project"><span className="document-icon"><FolderOpen size={18}/></span><span className="document-name"><b>Projects</b><small>Scope, status, timeline, and client details</small></span><ChevronRight size={16}/></Link><Link className="document-row" href="/documents"><span className="document-icon"><FileCheck2 size={18}/></span><span className="document-name"><b>Documents</b><small>Agreement, onboarding packet, and version history</small></span><ChevronRight size={16}/></Link><Link className="document-row" href="/invoices"><span className="document-icon"><ReceiptText size={18}/></span><span className="document-name"><b>Invoices</b><small>Deposit and final payment records</small></span><ChevronRight size={16}/></Link></div></div><aside className="side-column"><section className="note-panel"><p className="eyebrow">PAYMENT SAFETY</p><h2>PayPal is verified in Sandbox.</h2><p>No customer can be charged until a real invoice is issued and PayPal is switched to Live in Vercel Production.</p><Link href="/invoices">Open invoices <ArrowUpRight size={14}/></Link></section><section className="timeline"><p className="eyebrow">NEXT ACTIONS</p><div><span className="timeline-dot current"/><p><b>Create your first project</b><small>Required before document or invoice generation</small></p></div><div><span className="timeline-dot"/><p><b>Configure client sign-in</b><small>Magic-link authentication is the next security step</small></p></div><div><span className="timeline-dot"/><p><b>Generate agreement</b><small>Available after project setup</small></p></div></section></aside></section>
  </div>;
}
