"use client";
import Link from "next/link";
import { BriefcaseBusiness, FileText, FolderOpen, LayoutDashboard, Menu, ReceiptText, Settings, Users, X } from "lucide-react";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { ThemeToggle } from "./theme-toggle";
const clientNav=[[LayoutDashboard,"Overview","/"],[FolderOpen,"Project","/project"],[FileText,"Documents","/documents"],[ReceiptText,"Invoices","/invoices"],[FolderOpen,"Files","/files"],[Settings,"Settings","/settings"]] as const;
const adminNav=[[LayoutDashboard,"Dashboard","/admin"],[BriefcaseBusiness,"Projects","/admin/projects"],[Users,"Clients","/admin/clients"],[FileText,"Inquiries","/admin/inquiries"],[ReceiptText,"Payments","/admin/payments"],[Settings,"Settings","/settings"]] as const;
export function PortalShell({children,role="client",projectPublicId}:{children:React.ReactNode;role?:"admin"|"client";projectPublicId?:string}){const [open,setOpen]=useState(false);const pathname=usePathname(),nav=role==="admin"?adminNav:clientNav;const active=nav.find(([, ,href])=>href==="/admin"?pathname==="/admin":pathname===href||pathname.startsWith(`${href}/`))?.[1]??(role==="admin"?"Dashboard":"Overview");const destination=(href:string)=>role==="client"&&projectPublicId&&href!=="/settings"?`${href}?project=${encodeURIComponent(projectPublicId)}`:href;return <div className="app-shell"><aside className={`sidebar ${open?"sidebar-open":""}`}><div className="brand"><span className="brand-mark">R</span><span>Rezo</span><button className="mobile-close icon-button" onClick={()=>setOpen(false)} aria-label="Close navigation"><X size={18}/></button></div><div className="workspace"><span className="avatar">{role==="admin"?"AD":"RW"}</span><span><b>{role==="admin"?"Admin workspace":"Client workspace"}</b><small>{role==="admin"?"Operations & records":"Projects & records"}</small></span></div><nav aria-label={`${role} navigation`}><p className="nav-label">{role==="admin"?"Administration":"Workspace"}</p>{nav.map(([Icon,label,href])=><Link key={label} className={`nav-link ${label===active?"active":""}`} href={destination(href)} onClick={()=>setOpen(false)}><Icon size={17}/><span>{label}</span></Link>)}</nav><div className="sidebar-footer"><span>Secure workspace</span></div></aside>{open&&<button className="backdrop" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<main className="main"><header className="topbar"><button className="mobile-menu icon-button" aria-label="Open navigation" onClick={()=>setOpen(true)}><Menu size={18}/></button><div className="crumb"><span>Rezo</span><b>/</b><strong>{active}</strong></div><div className="top-actions"><ThemeToggle/><Link className="profile" href="/settings" aria-label="Settings"><span className="avatar">{role==="admin"?"AD":"RW"}</span></Link></div></header>{children}</main></div>}
