"use client";
import { FormEvent, useState } from "react";
import { ArrowRight, CheckCircle2 } from "lucide-react";

export function SetupForm() {
  const [status, setStatus] = useState<string | null>(null), [error, setError] = useState<string | null>(null), [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(null); setStatus(null); const response = await fetch("/api/setup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const payload = await response.json() as { error?: string; projectPublicId?: string; invoicePublicId?: string }; setLoading(false); if (!response.ok) return setError(payload.error ?? "Could not create the project."); setStatus(`Created ${payload.projectPublicId} and deposit invoice ${payload.invoicePublicId}.`); event.currentTarget.reset(); }
  return <form className="setup-form" onSubmit={submit}><div className="form-grid"><label>Client / company name<input name="clientName" required /></label><label>Client contact name<input name="contactName" required /></label><label>Client contact email<input name="contactEmail" type="email" required /></label><label>Project name<input name="projectName" required /></label><label>Project total<input name="totalAmount" inputMode="decimal" placeholder="1200.00" required /></label><label>Currency<select name="currency" defaultValue="EUR"><option>EUR</option><option>DZD</option><option>USD</option></select></label></div><label>Agreed scope<textarea name="scope" minLength={10} required placeholder="Describe the agreed website or web application scope." /></label>{error && <p className="form-error">{error}</p>}{status && <p className="form-success"><CheckCircle2 size={16}/>{status}</p>}<button className="button" disabled={loading}>{loading ? "Creating project..." : <>Create project and deposit invoice <ArrowRight size={16}/></>}</button></form>;
}
