import { createHash } from "crypto";
import { env } from "@/lib/env";
export type DocumentLocale="fr"|"en";
export type ProjectDocument={projectId:string;clientName:string;projectName:string;locale:DocumentLocale;templateVersion:string;scope:string;amount:string;currency:string;invoiceId?:string;dueAt?:Date|null;portalUrl?:string};
const css=`@page{size:A4;margin:0}*{box-sizing:border-box}body{margin:0;background:#050505;color:#f7f7f5;font-family:Arial,sans-serif;line-height:1.5}.page{min-height:297mm;padding:26mm 22mm;background:#050505}.hero{padding-top:27mm}h1{font-family:'Helvetica Neue',Arial,sans-serif;font-size:58pt;line-height:.94;letter-spacing:-.07em;font-weight:400;margin:0 0 32mm}h2{font-family:'Helvetica Neue',Arial,sans-serif;font-size:31pt;letter-spacing:-.055em;font-weight:400;margin:0 0 15mm}h3{font-size:15pt;margin:12mm 0 4mm;font-weight:400}p,li{font-size:12pt;margin:0 0 6mm}.muted{color:#bcbcb6}.eyebrow{font-size:8pt;letter-spacing:.14em;text-transform:uppercase;color:#bcbcb6;margin-bottom:9mm}.rule{border-top:1px solid #70706d;margin:14mm 0}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8mm 16mm}.meta b{display:block;font-size:8pt;text-transform:uppercase;letter-spacing:.1em;color:#bcbcb6;font-weight:400}.meta span{display:block;font-size:12pt;margin-top:2mm}.total{font-size:28pt;letter-spacing:-.05em;margin:8mm 0}.line{border-top:1px solid #777;padding:5mm 0;display:flex;justify-content:space-between;gap:12mm}.small{font-size:9.5pt;color:#c7c7c3}ul{padding-left:6mm}li{padding-left:3mm;margin-bottom:3mm}`;
const esc=(v:string)=>v.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]!));
const shell=(title:string,body:string)=>`<!doctype html><html><head><meta charset="utf-8"><style>${css}</style></head><body>${body}</body></html>`;
export function agreementHtml(d:ProjectDocument){const fr=d.locale==="fr";return shell(fr?"Accord de prestation":"Service agreement",`<main class="page"><p class="eyebrow">Rezo · ${esc(d.projectId)}</p><h1>${fr?"Accord de<br>prestation":"Service<br>agreement"}</h1><p>${fr?"Le présent accord définit les services, livrables et conditions de règlement convenus entre les parties.":"This agreement records the services, deliverables, and payment terms agreed by the parties."}</p><div class="rule"></div><div class="meta"><div><b>Client</b><span>${esc(d.clientName)}</span></div><div><b>Project</b><span>${esc(d.projectName)}</span></div><div><b>${fr?"Périmètre":"Scope"}</b><span>${esc(d.scope)}</span></div><div><b>${fr?"Montant":"Project total"}</b><span>${esc(d.amount)} ${esc(d.currency)}</span></div></div><h3>${fr?"Conditions":"Terms"}</h3><p>${fr?"Toute modification substantielle requiert un accord écrit. Les droits sur les livrables sont transférés après règlement intégral.":"Material changes require written agreement. Rights in the deliverables transfer after full payment."}</p></main>`)}
export function welcomeHtml(d:ProjectDocument){const fr=d.locale==="fr";return shell(fr?"Bienvenue":"Welcome",`<main class="page hero"><p class="eyebrow">Rezo · ${esc(d.projectName)}</p><h1>${fr?"Bienvenue":"Welcome"}</h1><p>${fr?`Bonjour ${esc(d.clientName)}, merci de nous confier votre projet. Votre espace Rezo rassemble les documents, paiements et prochains jalons.`:`Hi ${esc(d.clientName)}, thank you for choosing Rezo. Your workspace keeps documents, payments, and next milestones in one place.`}</p><h3>${fr?"Pour commencer":"To get started"}</h3><ul><li>${fr?"Acceptez l'accord de prestation dans votre espace.":"Accept the service agreement in your workspace."}</li><li>${fr?"Réglez l'acompte de 20 % indiqué sur votre facture.":"Pay the 20% deposit shown on your invoice."}</li><li>${fr?"Préparez les contenus, accès et éléments de marque nécessaires.":"Prepare the content, access, and brand assets needed for kickoff."}</li></ul><h3>${fr?"Comment nous travaillerons":"How we will work"}</h3><p>${fr?"Nous confirmons les objectifs et le périmètre, préparons la structure et le design, réalisons le travail convenu, puis organisons la revue et la livraison.":"We confirm goals and scope, prepare structure and design, build the agreed work, then organize review and delivery."}</p><p class="small">${fr?"Canaux principaux : e-mail et WhatsApp. Les demandes de communication restent en dehors du portail.":"Primary channels: email and WhatsApp. Communication remains outside the portal."}</p></main>`)}
export function invoiceHtml(d:ProjectDocument){const fr=d.locale==="fr";const ccp=d.currency==="DZD"?`${env.CCP_ACCOUNT_HOLDER??"CCP account holder"} · ${env.CCP_ACCOUNT_NUMBER??"CCP account number"} · RIP ${env.CCP_RIP??"CCP RIP"}`:"Pay securely through the PayPal action in your Rezo workspace.";return shell(fr?"Facture":"Invoice",`<main class="page"><p class="eyebrow">Rezo · ${esc(d.invoiceId??"Invoice")}</p><h1>${fr?"Facture":"Invoice"}</h1><div class="meta"><div><b>${fr?"Client":"Bill to"}</b><span>${esc(d.clientName)}</span></div><div><b>${fr?"Projet":"Project"}</b><span>${esc(d.projectName)}</span></div><div><b>${fr?"Échéance":"Due date"}</b><span>${d.dueAt?.toLocaleDateString(d.locale)??"—"}</span></div><div><b>${fr?"Devise":"Currency"}</b><span>${esc(d.currency)}</span></div></div><div class="rule"></div><div class="line"><span>${fr?"Acompte de 20 %":"20% deposit"}</span><span>${esc(d.amount)} ${esc(d.currency)}</span></div><p class="total">${esc(d.amount)} ${esc(d.currency)}</p><h3>${fr?"Instructions de paiement":"Payment instructions"}</h3><p>${esc(ccp)}</p><p class="small">${fr?"Veuillez indiquer le numéro de facture avec votre paiement.":"Please include the invoice number with your payment."}</p></main>`)}
export const documentHash=(html:string)=>createHash("sha256").update(html).digest("hex");
