import { NextRequest, NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { requireAdmin } from "@/lib/authz";
import { db } from "@/lib/db";
import { auditEvents, clientContacts, projects, users } from "@/lib/db/schema";
import { generateProjectDocument } from "@/lib/document-service";
import { accountEmail, sendProjectEmail, smtpConfigured } from "@/lib/mailer";
import { issueEmailToken } from "@/lib/email-tokens";
export async function POST(request:NextRequest,{params}:{params:Promise<{projectId:string}>}){const admin=await requireAdmin(),id=(await params).projectId;const project=await db.query.projects.findFirst({where:eq(projects.id,id)});if(!project)return NextResponse.json({error:"Project not found."},{status:404});const row=(await db.select({contact:clientContacts,user:users}).from(clientContacts).leftJoin(users,eq(clientContacts.userId,users.id)).where(and(eq(clientContacts.clientId,project.clientId),eq(clientContacts.isPrimary,true))).limit(1))[0];if(!row?.user)return NextResponse.json({error:"No linked primary contact."},{status:400});if(!smtpConfigured())return NextResponse.json({error:"Email delivery is not configured."},{status:400});try{const [invoice,welcome]=await Promise.all([generateProjectDocument(id,"invoice"),generateProjectDocument(id,"welcome_packet")]),token=row.user.status!=="active"?await issueEmailToken(row.user.id,"invite"):undefined,copy=token?accountEmail("invite",token,row.user.locale):undefined;await sendProjectEmail({to:row.contact.email,subject:copy?.subject??`New Rezo project: ${project.name}`,html:`${welcome.html}<p>${copy?.body??"Your Rezo workspace has been updated."}</p><p><a href="${copy?.href??`${request.nextUrl.origin}/sign-in`}">Open Rezo</a></p>`,attachments:[{filename:invoice.filename,content:invoice.pdf,contentType:"application/pdf"},{filename:welcome.filename,content:welcome.pdf,contentType:"application/pdf"}]});await db.insert(auditEvents).values({actorId:admin.id,entityType:"project",entityId:id,action:"project_delivery_resent",metadata:{email:row.contact.email}});return NextResponse.json({ok:true});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Delivery failed."},{status:500})}}
